# 1. 현재 사용 중인 버스정류장만 추출

In [1]:
import pandas as pd

path = r'D:\jeju_bus_data_no_leakage\station'.replace('\\', '/')
file_name = path + '/station_제주연구원_20190531.csv'

df = pd.read_csv(file_name, 
                 usecols = ['STATION_ID', 'STATION_NM', 'CENTER_YN', 'LOCAL_X', 'LOCAL_Y', 'USE_YN', 'STATION_ADDR'],
                 encoding = 'ansi')

df = df.query("USE_YN == 'Y'")

In [5]:
df.head(5) # 테스트

   STATION_ID STATION_NM CENTER_YN     LOCAL_X    LOCAL_Y USE_YN STATION_ADDR
0   405000152    남서광마을입구         N  126.521267  33.499683      Y     제주시 삼도1동
1   405000156       한국병원         N  126.518076  33.500054      Y     제주시 삼도1동
2   405000158       용천마을         N  126.519950  33.501547      Y     제주시 삼도1동
3   405000163        보건소         N  126.522067  33.492117      Y      제주시 도남동
7   405000169      광양사거리         N  126.527103  33.500473      Y     제주시 이도1동

# 2. 버스정류장 주소(STATION_ADDR)가 
# 결측된 행만 추출 → csv로 저장

In [90]:
addr_correct_df = df[df['STATION_ADDR'].notnull()] # 정류장주소가 결측되지 않은 행 추출

In [92]:
addr_missing_df = df[df['STATION_ADDR'].isnull()][df.columns[:-1]]

In [93]:
addr_missing_df.head(5) # 테스트

     STATION_ID STATION_NM CENTER_YN     LOCAL_X    LOCAL_Y USE_YN
27    405000209      제대아파트         N  126.557353  33.458783      Y
166   406000488        색달동         N  126.412267  33.261767      Y
173   406000498     예비군훈련장         N  126.574907  33.288083      Y
176   406000503      스위트호텔         N  126.407669  33.249044      Y
187   406000529      중문사거리         N  126.431520  33.251640      Y

In [98]:
addr_missing_df.to_csv(path + '/' + 'station_addr_missing_df.csv', index=False, encoding='ansi')

# 3. Geocoder-XR SW(무료)에서
# station_addr_missing_df.csv를 읽어들여
# 각 행의 위/경도 값에 대응하는 주소를 변환
# → station_addr_tidying_df.shp.csv로 저장
#### http://www.gisdeveloper.co.kr/?p=4784 : geocoder 소프트웨어 다운로드 홈페이지

# 4. station_addr_tidying.shp.csv EDA

In [103]:
addr_tidying_df = pd.read_csv(path + '/' + 'station_addr_tidying_df.shp.csv', encoding = 'ansi')

In [ ]:
del addr_tidying_df['No']

In [105]:
addr_tidying_df[addr_tidying_df['도로명주소'].isnull()] # 테스트

,STATION_ID,STATION_NM,CENTER_YN,LOCAL_X,LOCAL_Y,USE_YN,지번주소,도로명주소
112,405001942,국제여객선터미널,N,126.544529,33.524268,Y,제주특별자치도 제주시 건입동 908-11,NaN
135,405001988,금백조로입구,N,126.764565,33.447498,Y,제주특별자치도 제주시 구좌읍 송당리 2234-4,NaN
306,405002016,용눈이오름,N,126.831877,33.463512,Y,제주특별자치도 제주시 구좌읍 상도리 1397-3,NaN
311,405002029,아부오름,N,126.781359,33.446530,Y,제주특별자치도 제주시 구좌읍 송당리 산 174-1,NaN
316,405002012,다랑쉬오름 입구(북),N,126.829887,33.486079,Y,제주특별자치도 제주시 구좌읍 세화리 3637,NaN
319,405002017,용눈이오름,N,126.832178,33.463282,Y,제주특별자치도 제주시 구좌읍 종달리 4648,NaN
325,405002009,둔지오름,N,126.797756,33.506106,Y,제주특별자치도 제주시 구좌읍 한동리 산 40,NaN
329,405002010,둔지오름,N,126.797957,33.506151,Y,제주특별자치도 제주시 구좌읍 한동리 4848,NaN
331,405002028,아부오름,N,126.781119,33.446295,Y,제주특별자치도 제주시 구좌읍 송당리 산 168,NaN
332,405002013,다랑쉬오름 입구(북),N,126.829632,33.485949,Y,제주특별자치도 제주시 구좌읍 세화리 3637,NaN
592,406001762,백약이오름,N,126.794630,33.441035,Y,제주특별자치도 서귀포시 표선면 성읍리 1892,NaN
597,405002315,백약이오름,N,126.794258,33.441377,Y,제주특별자치도 제주시 구좌읍 송당리 산 244-1,NaN
620,405001987,금백조로입구,N,126.765371,33.447682,Y,제주특별자치도 제주시 구좌읍 송당리 2236-8,NaN
732,405002336,명도암입구 삼거리,N,126.640154,33.427615,Y,제주특별자치도 제주시 조천읍 교래리 산 137-25,NaN
735,405002337,명도암입구 삼거리,N,126.640442,33.427574,Y,제주특별자치도 제주시 조천읍 교래리 777-2,NaN
856,405002390,들위오름,N,126.540246,33.425478,Y,제주특별자치도 제주시 오등동 산 150-12,NaN
868,405002389,들위오름,N,126.539733,33.425932,Y,제주특별자치도 제주시 오등동 산 150-20,NaN

In [106]:
addr_tidying_df[addr_tidying_df['지번주소'].isnull()] # 테스트

,STATION_ID,STATION_NM,CENTER_YN,LOCAL_X,LOCAL_Y,USE_YN,지번주소,도로명주소
866,405002394,신엄포구,N,126.349898,33.473054,Y,NaN,제주특별자치도 제주시 애월읍 애월해안로 390

## result.shp.csv 확인 결과 '지번주소' 변환 실패 건수가 
## 더 적으므로 '지번주소'를 'STATION_ADDR'로 사용.
## (단, 지번주소가 NaN인 행은 도로명주소 필드를 사용.)

In [107]:
jibeon_juso_missing_df = addr_tidying_df[addr_tidying_df['지번주소'].isnull()]

In [108]:
addr_tidying_df.loc[jibeon_juso_missing_df.index, '지번주소'] =\
    jibeon_juso_missing_df.loc[:, '도로명주소']

In [109]:
addr_tidying_df.query('STATION_ID == 405002394') # 테스트 (지번주소가 tidying되었나)

,STATION_ID,STATION_NM,CENTER_YN,LOCAL_X,LOCAL_Y,USE_YN,지번주소,도로명주소
866,405002394,신엄포구,N,126.349898,33.473054,Y,제주특별자치도 제주시 애월읍 애월해안로 390,제주특별자치도 제주시 애월읍 애월해안로 390

In [110]:
addr_tidying_df = addr_tidying_df.rename(columns = {'지번주소': 'STATION_ADDR'})

In [111]:
addr_tidying_df.loc[:, 'STATION_ADDR'] =\
    addr_tidying_df['STATION_ADDR'].apply(lambda obj: ' '.join(str(obj).split(' ')[1:]))

In [113]:
del addr_tidying_df['도로명주소']

In [114]:
addr_tidying_df.head() # 테스트

,STATION_ID,STATION_NM,CENTER_YN,LOCAL_X,LOCAL_Y,USE_YN,STATION_ADDR
0,405000209,제대아파트,N,126.557353,33.458783,Y,제주시 아라일동 349-5
1,406000488,색달동,N,126.412267,33.261767,Y,서귀포시 색달동 3383
2,406000498,예비군훈련장,N,126.574907,33.288083,Y,서귀포시 토평동 3058-3
3,406000503,스위트호텔,N,126.407669,33.249044,Y,서귀포시 색달동 2798-7
4,406000529,중문사거리,N,126.431520,33.251640,Y,서귀포시 중문동 2774

# 5. addr_tidying_df와 addr_correct_df 합집합(concat)

In [117]:
result = pd.concat([addr_correct_df, addr_tidying_df], ignore_index=True)
result

,STATION_ID,STATION_NM,CENTER_YN,LOCAL_X,LOCAL_Y,USE_YN,STATION_ADDR
0,405000152,남서광마을입구,N,126.521267,33.499683,Y,제주시 삼도1동
1,405000156,한국병원,N,126.518076,33.500054,Y,제주시 삼도1동
2,405000158,용천마을,N,126.519950,33.501547,Y,제주시 삼도1동
3,405000163,보건소,N,126.522067,33.492117,Y,제주시 도남동
4,405000169,광양사거리,N,126.527103,33.500473,Y,제주시 이도1동
5,405000171,탐라장애인 종합복지관,N,126.525833,33.500017,Y,제주시 이도1동
6,405000173,남서광마을,N,126.523759,33.499789,Y,제주시 삼도1동
7,405000176,월구마을,N,126.507000,33.500133,Y,제주시 오라3동
8,405000177,오라3동,N,126.503183,33.499250,Y,제주시 오라3동
9,405000178,명신마을,N,126.503028,33.499623,Y,제주시 용담2동
10,405000180,명주주택,N,126.493758,33.495670,Y,제주시 연동
11,405000181,문서교,N,126.614191,33.528154,Y,제주시 조천읍 신촌리
12,405000183,진드르,N,126.608128,33.524196,Y,서귀포시 표선면 가시리
13,405000184,진드르,N,126.606917,33.523667,Y,제주시 조천읍 신촌리
14,405000191,은남동,N,126.490897,33.485822,Y,제주시 연동
15,405000194,도호동,N,126.495011,33.485810,Y,제주시 연동
16,405000199,함덕리(4구),N,126.673231,33.539982,Y,제주시 조천읍 함덕리
17,405000202,신사동,N,126.675754,33.534836,Y,제주시 조천읍 함덕리
18,405000203,신사동,N,126.675601,33.534663,Y,제주시 조천읍 함덕리
19,405000207,제주대학교,N,126.561624,33.459893,Y,제주시 아라2동
20,405000210,제대아파트,N,126.557300,33.458900,Y,제주시 아라동
21,405000215,제주대학교입구,N,126.550757,33.456718,Y,제주시 아라동
22,405000217,서해아파트,N,126.541533,33.504883,Y,제주시 일도2동
23,406000404,향토오일시장,N,126.575167,33.267433,Y,서귀포시 동홍동
24,406000405,대포동,N,126.431682,33.242927,Y,서귀포시 대포동
25,406000410,제석공원,N,126.567310,33.246120,Y,서귀포시 서귀동
26,406000411,서귀포 YWCA,N,126.565292,33.244572,Y,서귀포시 서귀동
27,405000356,수협제주도지회,N,126.495217,33.489700,Y,제주시 연동
28,405000358,이호동 동마을,N,126.460950,33.500300,Y,제주시 이호1동
29,405000360,이호동주민센터,N,126.458267,33.498767,Y,제주시 이호1동
...,...,...,...,...,...,...,...
3780,405002395,신엄포구,N,126.350005,33.472977,Y,제주시 애월읍 고내리 337-2
3781,406001859,신산퐁낭거리,N,126.876702,33.383083,Y,서귀포시 성산읍 신산리 1009-2
3782,405002390,들위오름,N,126.540246,33.425478,Y,제주시 오등동 산 150-12
3783,406001854,진동산,N,126.827298,33.363311,Y,서귀포시 성산읍 신풍리 1728
3784,405002387,마방목지,N,126.603313,33.427032,Y,제주시 용강동 산 14-26
3785,406001855,진동산,N,126.827346,33.363195,Y,서귀포시 성산읍 신풍리 1386
3786,405002392,고내포구,N,126.336837,33.467285,Y,제주시 애월읍 고내리 1156-4
3787,405002396,신엄입구,N,126.363457,33.478485,Y,제주시 애월읍 신엄리 2730-4
3788,406001860,추사유배지,NaN,126.279054,33.249106,Y,서귀포시 대정읍 인성리 208-1
3789,405002386,평화양로원,N,126.614896,33.465227,Y,제주시 봉개동 227-36
3790,406001858,신풍하동큰개,N,126.863937,33.362906,Y,서귀포시 성산읍 신풍리 71-4
3791,406001857,도래기소입구,N,126.832385,33.361277,Y,서귀포시 성산읍 신풍리 917-3
3792,405002394,신엄포구,N,126.349898,33.473054,Y,제주시 애월읍 애월해안로 390
3793,406001856,도래기소입구,NaN,126.832316,33.361436,Y,서귀포시 성산읍 신풍리 937
3794,405002389,들위오름,N,126.539733,33.425932,Y,제주시 오등동 산 150-20
3795,405002393,고내포구,N,126.337175,33.467098,Y,제주시 애월읍 고내리 1156-4
3796,405002401,가문동마을길,N,126.395767,33.483513,Y,제주시 애월읍 하귀2리 2615-2
3797,405002398,구엄포구,N,126.377559,33.484071,Y,제주시 애월읍 구엄리 606
3798,405002400,가문동마을길,N,126.395788,33.483592,Y,제주시 애월읍 하귀2리 2615-5
3799,405002397,신엄입구,N,126.363448,33.478401,Y,제주시 애월읍 신엄리 2730-3
3800,405002399,구엄포구,N,126.377809,33.484062,Y,제주시 애월읍 구엄리 605-5
3801,405002381,일도초등학교,N,126.528775,33.510870,Y,제주시 일도일동 1100-38
3802,406001852,제주신화월드 소방서,N,126.307171,33.302909,Y,서귀포시 안덕면 서광리 산 35-15
3803,406001853,제주신화월드 소방서,N,126.306134,33.302819,Y,서귀포시 안덕면 서광리 산 35-7
3804,406001850,수산2리 입구,N,126.872195,33.438797,Y,서귀포시 성산읍 수산리 4764
3805,406001849,수산2리 입구,N,126.872212,33.438924,Y,서귀포시 성산읍 수산리 1655
3806,406001851,토산2리사무소,N,126.779692,33.308664,Y,서귀포시 표선면 토산리 537-2
3807,406001844,진동산,N,126.794736,33.333259,Y,서귀포시 표선면 세화리 2489
3808,406001845,중문요양원,N,126.430084,33.262566,Y,서귀포시 중문동 1114
3809,406001846,중문요양원,N,126.430098,33.262388,Y,서귀포시 중문동 2774

In [120]:
result.to_csv(path + '/' + 'station_final.csv', encoding='ansi', index=False)